# Generated by Django 2.1.7 on 2019-06-19 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_vote', models.IntegerField(default=1, null=True)),
                ('string', models.CharField(max_length=300, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pre_vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test1.Pre_Vote')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_vote', models.IntegerField(default=1, null=True)),
                ('string', models.CharField(max_length=300, null=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pre_vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test1.Pre_Vote')),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='pre_vote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='travel',
        ),
        migrations.AlterField(
            model_name='travel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='passenger_vote',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.Travel'),
        ),
        migrations.AddField(
            model_name='driver_vote',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.Travel'),
        ),
    ]
