# Generated by Django 2.1.7 on 2019-06-21 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_auto_20190619_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test1.Driver'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test1.Passenger'),
        ),
    ]
